kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: ${APP_NAME}
  annotations:
    description: Site Web qui permet la création d'une demande de generation de certificat numérique pour l'ICP d'X-Road. 
    tags: cqen, experimentation, x-road, icp, pki
objects:

# CSR-controller
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: ${APP_NAME}
    labels:
      app.kubernetes.io/part-of: ${APP_GROUP}
- kind: BuildConfig
  apiVersion: v1
  metadata:
    annotations:
      app.openshift.io/vcs-uri: ${GITHUB_REPOSITORY_URI}
      template.alpha.openshift.io/wait-for-ready: "true"
    labels:
      app: ${APP_NAME}
      app.kubernetes.io/part-of: ${APP_GROUP}
    name: ${APP_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APP_NAME}:latest
    source:
      contextDir: ${CONTEXT_SOURCE_DIR}
      git:
        uri: ${GITHUB_REPOSITORY_URI}
        ref: ${GIT_REF}
      type: Git
    strategy:
      dockerStrategy:
        dockerfilePath: dockerfile
      type: Docker
    triggers:
      - github:
          secretReference:
            name: csr-build
        type: GitHub
      - type: ConfigChange
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: ${APP_NAME}
    labels:
      app: ${APP_NAME}
      app.kubernetes.io/part-of: CSR
  spec:
    strategy:
      type: Rolling
      rollingParams:
        updatePeriodSeconds: 1
        intervalSeconds: 1
        timeoutSeconds: 600
        maxUnavailable: 25%
        maxSurge: 25%
      resources: {}
      activeDeadlineSeconds: 21600
    triggers:
      - github:
          secretReference:
            name: csr-build
        type: GitHub
      - type: ConfigChange
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - ${APP_NAME}
          from:
            kind: ImageStreamTag
            name: "${APP_NAME}:latest"
    replicas: 1
    revisionHistoryLimit: 10
    test: false
    selector:
      app: ${APP_NAME}
    template:
      metadata:
        labels:
          app: ${APP_NAME}
          app.kubernetes.io/part-of: ${APP_GROUP} 
      spec:
        containers:
          - name: ${APP_NAME}
            image: " "
            ports:
              - containerPort: 3000
                protocol: TCP
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            imagePullPolicy: Always
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler
- kind: Service
  apiVersion: v1
  metadata:
    name: ${APP_NAME}
    labels:
      app: ${APP_NAME}
      app.kubernetes.io/part-of: ${APP_GROUP}
  spec:
    selector:
      app: ${APP_NAME}
    ports:
      - name: "3000"
        protocol: TCP
        port: 3000
        targetPort: 3000
- kind: Route
  apiVersion: v1
  metadata:
    name: ${APP_NAME}
    labels:
      app: ${APP_NAME}
      app.kubernetes.io/part-of: ${APP_GROUP}
  spec:
    host: ${APP_NAME}.apps.exp.openshift.cqen.ca
    to:
      kind: Service
      name: ${APP_NAME}
      weight: 100
    port:
      targetPort: 3000
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: None
    wildcardPolicy: None
  status:
    ingress:
      - host: ${APP_NAME}.apps.exp.openshift.cqen.ca 
        routerName: default
        conditions:
          - type: Admitted
            status: "True"
        wildcardPolicy: None
        routerCanonicalHostname: apps.exp.openshift.cqen.ca
######################################################################
# Parameters
######################################################################
parameters:
- name: APP_GROUP
  displayName: App Group
  description: Used to group components together.
  required: true
  value: 'ICP-XRoad' 
- name: APP_NAME
  displayName: Application name
  description: Used to group components together in the OpenShift console.
  required: true
  value: 'csr-controller'
- name: GITHUB_REPOSITORY_URI
  displayName: GitHub repository URI
  description: URI of the GitHub repository.
  required: true
  value: https://github.com/torjc01/csr-generator.git
- name: CONTEXT_SOURCE_DIR
  displayName: Context source dir
  description: Répertoire ou sont les elements pour le build (notamment Dockerfile).
  required: false
  value: CSR
- name: GIT_REF
  displayName: Git reference
  description: Dénomination de la branche que sera utilisée pour le build.
  required: true
  value: prod